# Site settings
title: 
header-img: img/home-bg.png
email: pmknyc@optimum.net
copyright_name: pmknyc
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: pmknyc
github_username:  pmknyc
learn_profile: pmknyc
email_username: pmknyc@optimum.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
